# Generated by Django 4.2.7 on 2024-02-20 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_test_alter_user_paid_tests'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='accounts.test'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tests', to='accounts.test'),
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
