# Generated by Django 5.0.2 on 2024-02-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_answer_answer_image_question_question_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertest',
            name='incorrect_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses_tests/answer_images/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses_tests/question_images/'),
        ),
    ]
