# Generated by Django 5.0.2 on 2024-03-07 19:56

import courses.image_load
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255, verbose_name='Название')),
                ('difficulty', models.CharField(max_length=40, verbose_name='Сложность')),
                ('test_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=4, verbose_name='Тип')),
                ('countdown', models.DurationField(blank=True, default=None, null=True)),
                ('course', models.ManyToManyField(related_name='online_tests', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Онлайн тест',
                'verbose_name_plural': 'Онлайн тесты',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=255, verbose_name='Название')),
                ('question_text', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to=courses.image_load.QuestionUpload._upload, verbose_name='Изображение')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='online_tests.onlinetest', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопросы',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(verbose_name='Правильный')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('answer_image', models.ImageField(blank=True, null=True, upload_to=courses.image_load.AnswerUpload._upload, verbose_name='Изображение')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='online_tests.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответ',
            },
        ),
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=0)),
                ('correct_answer_count', models.IntegerField(default=0)),
                ('incorrect_answer_cnt', models.IntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tests', to='online_tests.onlinetest', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тесты ученика',
                'verbose_name_plural': 'Тесты ученика',
                'unique_together': {('user', 'test')},
            },
        ),
    ]
