# Generated by Django 5.0.3 on 2024-04-16 07:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinetest',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='onlinetest',
            name='test_language',
            field=models.CharField(choices=[('русский', 'Ru'), ('кыргызский', 'Kg')], default='кыргызский', max_length=10, verbose_name='Язык курса'),
        ),
        migrations.AddField(
            model_name='usertest',
            name='test_end',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usertest',
            name='test_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
