# Generated by Django 5.0.2 on 2024-03-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_tests', '0002_alter_answer_answer_image_and_more'),
        ('online_tests', '0002_answer_answer_image_question_question_image_and_more'),
    ]

    operations = [
    ]
