# Generated by Django 5.0.2 on 2024-03-05 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_course_image'),
        ('online_tests', '0003_merge_20240302_1719'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='OnlineTest',
        ),
        migrations.AlterModelOptions(
            name='onlinetest',
            options={'verbose_name': 'Онлайн тест', 'verbose_name_plural': 'Онлайн тесты'},
        ),
        migrations.RenameField(
            model_name='usertest',
            old_name='correct_answers',
            new_name='correct_answer_count',
        ),
        migrations.RenameField(
            model_name='usertest',
            old_name='incorrect_answers',
            new_name='incorrect_answer_cnt',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='date_taken',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='test',
        ),
        migrations.AlterField(
            model_name='usertest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
