# Generated by Django 5.0.2 on 2024-03-03 22:23

import courses.image_load
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_course_image'),
        ('online_tests', '0003_merge_20240302_1719'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответ'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопросы', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Онлайн тест', 'verbose_name_plural': 'Онлайн тесты'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Ответы учеников', 'verbose_name_plural': 'Ответы учеников'},
        ),
        migrations.AlterModelOptions(
            name='usertest',
            options={'verbose_name': 'Тесты ученика', 'verbose_name_plural': 'Тесты ученика'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to=courses.image_load.AnswerUpload._upload, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(verbose_name='Правильный'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='online_tests.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to=courses.image_load.QuestionUpload._upload, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='online_tests.test', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='test',
            name='course',
            field=models.ManyToManyField(related_name='online_tests', to='courses.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='test',
            name='difficulty',
            field=models.CharField(max_length=40, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=4, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='online_tests.answer', verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='online_tests.question', verbose_name='Вопросы'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='online_tests.usertest', verbose_name='Тесты учеников'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='correct_answers',
            field=models.IntegerField(default=0, verbose_name='Правильные ответы'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата тестирование'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='incorrect_answers',
            field=models.IntegerField(default=0, verbose_name='Неправильные ответы'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tests', to='online_tests.test', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
