# Generated by Django 5.0.2 on 2024-03-05 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_tests', '0004_rename_test_onlinetest_alter_onlinetest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertest',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tests', to='online_tests.onlinetest'),
        ),
        migrations.AlterUniqueTogether(
            name='usertest',
            unique_together={('user', 'test')},
        ),
    ]
