# Generated by Django 5.0.3 on 2024-05-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Учитель', 'Teacher'), ('Пользователь', 'User')], default='Пользователь', max_length=30, verbose_name='Должность'),
        ),
    ]
