# Generated by Django 5.0.2 on 2024-03-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('user', 'User')], default='user', max_length=30, verbose_name='Должность'),
        ),
    ]
