# Generated by Django 5.0.2 on 2024-02-27 20:26

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageFlatText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Название страницы')),
                ('path', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Путь до страницы')),
                ('text_primary', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Основной блок')),
                ('text_secondary', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Дополнительный блок')),
            ],
            options={
                'verbose_name': 'Содержание страницы',
                'verbose_name_plural': 'Содержание страницы',
            },
        ),
    ]
