# Generated by Django 5.0.2 on 2024-02-27 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageflattext',
            options={'verbose_name': 'Тексты для страниц', 'verbose_name_plural': 'Тексты для страниц'},
        ),
    ]
