# Generated by Django 5.0.2 on 2024-02-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_pages', '0002_alter_pageflattext_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageflattext',
            name='path',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Путь до страницы'),
        ),
        migrations.AlterField(
            model_name='pageflattext',
            name='title',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Название страницы'),
        ),
    ]
