# Generated by Django 5.0.2 on 2024-02-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paid_tests',
            field=models.ManyToManyField(blank=True, to='tests.test'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
