# Generated by Django 4.2.7 on 2024-02-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('difficulty', models.CharField(max_length=40)),
                ('test_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='paid_tests',
            field=models.ManyToManyField(blank=True, to='accounts.test'),
        ),
    ]
