# Generated by Django 5.0.2 on 2024-02-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='paid_tests',
        ),
    ]
