# Generated by Django 5.0.2 on 2024-02-25 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_is_active_visit_is_currently_viewing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='datetime',
            new_name='lesson_date',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.course'),
        ),
    ]
