# Generated by Django 5.0.2 on 2024-03-12 17:04

import courses.image_load
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_pagemodel_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselAdvantagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.pagemodel', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Преимущества',
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.CreateModel(
            name='CarouselMainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=courses.image_load.HomeUpload._upload, verbose_name='Изображение')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.pagemodel', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Главная карусель',
                'verbose_name_plural': 'Главная карусель',
            },
        ),
        migrations.CreateModel(
            name='CarouselReviewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Имя')),
                ('review', models.TextField(verbose_name='Отзыв')),
                ('image', models.ImageField(upload_to=courses.image_load.HomeUpload._upload, verbose_name='Изображение')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.pagemodel', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='CarouselSponsorsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=courses.image_load.HomeUpload._upload, verbose_name='Изображение')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.pagemodel', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Спонсоры',
                'verbose_name_plural': 'Спонсоры',
            },
        ),
    ]
