# Generated by Django 5.0.2 on 2024-03-16 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_carouseladvantagesmodel_carouselmainmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouseladvantagesmodel',
            options={'verbose_name': 'Статичные блоки', 'verbose_name_plural': 'Статичные блоки'},
        ),
        migrations.AlterField(
            model_name='carouseladvantagesmodel',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adv', to='pages.pagemodel', verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='carouselmainmodel',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='pages.pagemodel', verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='carouselreviewsmodel',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pages.pagemodel', verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='carouselsponsorsmodel',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='pages.pagemodel', verbose_name='Страница'),
        ),
    ]
