# Generated by Django 5.0.2 on 2024-03-07 19:56

import courses.image_load
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255, verbose_name='Название курса')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_finish', models.DateField(verbose_name='Дата окончания')),
                ('course_image', models.ImageField(blank=True, null=True, upload_to=courses.image_load.CourseUpload._upload, verbose_name='Изображение')),
                ('paid_by', models.ManyToManyField(blank=True, limit_choices_to={'role': 'user'}, related_name='paid_courses', to=settings.AUTH_USER_MODEL, verbose_name='Те, кто оплатил')),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'user'}, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL, verbose_name='Ученики')),
                ('teacher', models.ManyToManyField(limit_choices_to={'role': 'teacher'}, related_name='courses_taught', to=settings.AUTH_USER_MODEL, verbose_name='Учители')),
            ],
            options={
                'verbose_name': 'Курсы',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название урока')),
                ('grade', models.PositiveIntegerField(verbose_name='Уровень')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Информация')),
                ('video', models.URLField(blank=True, null=True, verbose_name='Ссылка на запись урока')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('lesson_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=4, verbose_name='Бесплатный/платный')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Урок',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_currently_viewing', models.BooleanField()),
                ('visit_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата посеения')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='courses.lesson', verbose_name='Урок')),
                ('students', models.ForeignKey(blank=True, limit_choices_to={'role', 'user'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Посещения',
                'verbose_name_plural': 'Посещения',
            },
        ),
    ]
