# Generated by Django 5.0.2 on 2024-02-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='grade',
            field=models.TextField(max_length=5000),
        ),
    ]
