# Generated by Django 5.0.3 on 2024-04-16 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='grade',
        ),
        migrations.AddField(
            model_name='lesson',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер урока'),
        ),
        migrations.AddField(
            model_name='visit',
            name='grade',
            field=models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=5, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_course', to='courses.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='is_currently_viewing',
            field=models.CharField(blank=True, choices=[('Присутствовал', 'Присутствовал'), ('Отсутствовал', 'Отсутствовал')], default='', max_length=15, verbose_name='Посещение'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='students',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'user'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название группы')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_for_group', to='courses.course', verbose_name='Курс')),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'user'}, related_name='students_of_group', to=settings.AUTH_USER_MODEL, verbose_name='Ученики')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'user'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_of_group', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
        ),
        migrations.CreateModel(
            name='LessonPerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_lesson', to='courses.group', verbose_name='Группа')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_group', to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Урок у группы',
                'verbose_name_plural': 'Уроки у групп',
            },
        ),
        migrations.AlterField(
            model_name='visit',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='courses.lessonpergroup', verbose_name='Урок у группы'),
        ),
    ]
