# Generated by Django 5.0.3 on 2024-05-14 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursegroup',
            options={'verbose_name': 'Группа курсов', 'verbose_name_plural': 'Группы курсов'},
        ),
    ]
