# Generated by Django 5.0.2 on 2024-02-20 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='paid_by',
            field=models.ManyToManyField(blank=True, related_name='paid_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=4),
        ),
        migrations.AddField(
            model_name='visit',
            name='students',
            field=models.ForeignKey(blank=True, limit_choices_to={'role', 'user'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'user'}, null=True, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(limit_choices_to={'role': 'teacher'}, related_name='courses_taught', to=settings.AUTH_USER_MODEL),
        ),
    ]
