# Generated by Django 5.0.3 on 2024-05-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='group_type',
            field=models.CharField(choices=[('В группе', 'В группе'), ('Индивидуально', 'Индивидуально')], default='В группе', verbose_name='В группе/Индивидуально'),
        ),
    ]
