# Generated by Django 5.0.2 on 2024-02-20 20:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_visit_user_course_paid_by_lesson_lesson_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='is_active',
            new_name='is_currently_viewing',
        ),
        migrations.AlterField(
            model_name='course',
            name='paid_by',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'user'}, related_name='paid_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'user'}, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
