# Generated by Django 5.0.3 on 2024-05-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_paid_by_alter_course_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateTimeField(verbose_name='Дата посещения'),
        ),
    ]
