# Generated by Django 5.0.3 on 2024-05-14 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_visit_visit_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='paid_by',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'user'}, related_name='paid_courses', to=settings.AUTH_USER_MODEL, verbose_name='Те, кто оплатил'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'user'}, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL, verbose_name='Ученики'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(limit_choices_to={'role': 'teacher'}, related_name='courses_taught', to=settings.AUTH_USER_MODEL, verbose_name='Учители'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'user'}, related_name='students_of_group', to=settings.AUTH_USER_MODEL, verbose_name='Ученики'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_of_group', to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='students',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'user'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
    ]
