# Generated by Django 5.0.2 on 2024-02-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_options_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='...', verbose_name='Изображение'),
        ),
    ]
