# Generated by Django 5.0.2 on 2024-03-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=4, verbose_name='Бесплатный/платный'),
        ),
    ]
