# Generated by Django 5.0.2 on 2024-03-02 07:35

import courses.image_load
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to=courses.image_load.CourseUpload._upload, verbose_name='Изображение'),
        ),
    ]
