# Generated by Django 5.0.2 on 2024-03-07 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_course_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='courses.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='students',
            field=models.ForeignKey(blank=True, limit_choices_to={'role', 'user'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата посеения'),
        ),
    ]
