name: Build on Main with Docker
on: 
  push:
    branches:
      - main

jobs:
  test_job:
    name: Testing App
    runs-on: ubuntu-latest
    services:
      db_1:
        image: postgres:14.3
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres

    steps:
      - name: Download Project
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --no-cache-dir poetry 
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi --no-root
      - name: Run Tests
        run: |
          mv example.env .env
          cd source
          python manage.py makemigrations
          python manage.py migrate
          python manage.py test

  build_job:
    name: Build Images
    runs-on: ubuntu-latest
    permissions: write-all
    services:
      db_1:
        image: postgres:14.3
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres

    steps:
      - name: Download Project
        uses: actions/checkout@v4
      - name: Build and tag image
        run: |
          docker build . -t ghcr.io/${{github.repository}}:dev_latest 
          docker build . -t ghcr.io/${{github.repository}}:${GITHUB_SHA::8} 

      - name: Docker login
        run: docker login ghcr.io -u ${{github.actor}} -p ${{secrets.GITHUB_TOKEN}}
      - name: Publish image
        env:
          IMAGE_NAME: $GITHUB_REPOSITORY
        run: |
          docker push ghcr.io/${{github.repository}} --all-tags
